export default {
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    { name: 'seo', title: 'SEO & Social' },
    { name: 'tracking', title: 'Tracking' },
    { name: 'schema', title: 'Structured Data (Schema.org)' },
  ],
  fields: [
    {
      name: 'title',
      title: 'Site Title (browser tab)',
      type: 'string',
      description: 'Shown in the browser tab and as the default page title',
      validation: (Rule) => Rule.required(),
      group: 'seo',
    },
    {
      name: 'description',
      title: 'SEO Description',
      type: 'text',
      rows: 3,
      description: 'Shown in Google search results — keep under 160 characters',
      validation: (Rule) => Rule.max(160),
      group: 'seo',
    },
    {
      name: 'ogImage',
      title: 'Social Share Image',
      type: 'image',
      description: 'Preview image when shared on Facebook, LinkedIn, WhatsApp etc. Recommended 1200x630px',
      options: { hotspot: true },
      group: 'seo',
    },
    {
      name: 'gaId',
      title: 'Google Analytics Measurement ID',
      type: 'string',
      description: 'e.g. G-XXXXXXXXXX (leave blank to disable)',
      group: 'tracking',
    },
    {
      name: 'gtmId',
      title: 'Google Tag Manager ID',
      type: 'string',
      description: 'e.g. GTM-XXXXXXX (leave blank to disable)',
      group: 'tracking',
    },
    // ---- STRUCTURED DATA (Schema.org) ----
    {
      name: 'businessType',
      title: 'Business Type',
      type: 'string',
      description: 'Used by Google for the knowledge panel and rich results',
      options: {
        list: [
          { title: 'Physiotherapy Clinic', value: 'Physiotherapy' },
          { title: 'Medical Business', value: 'MedicalBusiness' },
          { title: 'Health & Beauty Business', value: 'HealthAndBeautyBusiness' },
          { title: 'Local Business (generic)', value: 'LocalBusiness' },
        ],
      },
      initialValue: 'Physiotherapy',
      group: 'schema',
    },
    {
      name: 'businessName',
      title: 'Business Name',
      type: 'string',
      description: 'The official name of the business (e.g. Balance Performance Physiotherapy)',
      group: 'schema',
    },
    {
      name: 'phone',
      title: 'Phone Number',
      type: 'string',
      description: 'Include country code, e.g. +44 20 7123 4567',
      group: 'schema',
    },
    {
      name: 'email',
      title: 'Contact Email',
      type: 'string',
      group: 'schema',
    },
    {
      name: 'streetAddress',
      title: 'Street Address',
      type: 'string',
      description: 'e.g. 123 High Street',
      group: 'schema',
    },
    {
      name: 'city',
      title: 'City / Town',
      type: 'string',
      group: 'schema',
    },
    {
      name: 'region',
      title: 'Region / County',
      type: 'string',
      description: 'e.g. London, Greater Manchester',
      group: 'schema',
    },
    {
      name: 'postalCode',
      title: 'Postal Code',
      type: 'string',
      group: 'schema',
    },
    {
      name: 'country',
      title: 'Country Code',
      type: 'string',
      description: 'Two-letter code, e.g. GB, US, IE',
      initialValue: 'GB',
      group: 'schema',
    },
    {
      name: 'latitude',
      title: 'Latitude',
      type: 'number',
      description: 'Optional. Helps Google Maps placement. Find via Google Maps → right-click location.',
      group: 'schema',
    },
    {
      name: 'longitude',
      title: 'Longitude',
      type: 'number',
      description: 'Optional. Pair with Latitude.',
      group: 'schema',
    },
    {
      name: 'priceRange',
      title: 'Price Range',
      type: 'string',
      description: 'Use £, ££, £££, or ££££',
      group: 'schema',
    },
    {
      name: 'openingHours',
      title: 'Opening Hours',
      type: 'array',
      description: 'Add one entry per day or grouped days',
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'days',
              title: 'Days',
              type: 'string',
              options: {
                list: [
                  { title: 'Monday', value: 'Mo' },
                  { title: 'Tuesday', value: 'Tu' },
                  { title: 'Wednesday', value: 'We' },
                  { title: 'Thursday', value: 'Th' },
                  { title: 'Friday', value: 'Fr' },
                  { title: 'Saturday', value: 'Sa' },
                  { title: 'Sunday', value: 'Su' },
                  { title: 'Mon–Fri', value: 'Mo-Fr' },
                  { title: 'Mon–Sat', value: 'Mo-Sa' },
                  { title: 'Sat–Sun', value: 'Sa-Su' },
                ],
              },
            },
            {
              name: 'opens',
              title: 'Opens',
              type: 'string',
              description: '24hr format, e.g. 08:00',
            },
            {
              name: 'closes',
              title: 'Closes',
              type: 'string',
              description: '24hr format, e.g. 18:00',
            },
          ],
          preview: {
            select: { days: 'days', opens: 'opens', closes: 'closes' },
            prepare({ days, opens, closes }) {
              return { title: `${days || '?'}: ${opens || '?'}–${closes || '?'}` }
            },
          },
        },
      ],
      group: 'schema',
    },
    {
      name: 'sameAs',
      title: 'Social / External Profile URLs',
      type: 'array',
      description: 'Full URLs for the business on Facebook, Instagram, LinkedIn, Google Business, etc. Helps Google verify identity.',
      of: [{ type: 'url' }],
      group: 'schema',
    },
  ],
  preview: {
    prepare() {
      return { title: 'Site Settings' }
    },
  },
}
